seeding:
  population_size: 12
  family_size_distribution: [4, 3, 3, 2]  # used cyclically if sum < population
  base_age_range: [18, 60]
  base_wealth_range: [20, 80]
  initial_reputation: [0.4, 0.8]
  shock_exposure_range: [0.1, 0.5]
  exploration_rate_range: [0.1, 0.4]
  reproduction_rate_range: [0.0, 0.1]
  network_bandwidth_range: [3, 7]
  memory_capacity_range: [3, 8]
  adaptability_range: [0.3, 0.8]
  risk_tolerance_range: [0.2, 0.8]
  norm_sensitivity_range: [0.2, 0.8]
  trust_disposition_range: [0.2, 0.8]
  patience_range: [0.2, 0.8]
  enforcement_aversion_range: [0.2, 0.8]
  reputation_sensitivity_range: [0.2, 0.8]
  lifespan_range: [60, 90]
environment:
  interaction_opportunity_rate: 1.1
  novel_pair_chance: 0.25
  information_fidelity: 0.8
  transaction_friction: 0.05
  production_rate: 0.6
  shocks:
    frequency: 0.1
    magnitude_mean: 8
    magnitude_std: 4
    story: "A macro shock ripples through the economy."
  inflow:
    amount: 6
    frequency: 0.25
    targets: "random_agents"
    story: "A universal stipend is distributed."
engine:
  max_pair_opps_per_step: 10
  max_prod_ops_per_step: 6
  max_tokens_per_step: 2048
  max_prod_value_per_node: 50
  top_k_edges: 3
  top_m_memories: 3
  strength_activation_threshold: 0.05
  job_change_rate: 0.1
  succession_update_rate: 0.05
  succession_templates:
    - "Leave assets to eldest kin."
    - "Distribute equally among siblings."
    - "Donate excess to family institution."
  birth_rate: 0.05
  birth_trait_noise: 0.1
  initial_child_reputation_range: [0.4, 0.7]
  max_children_per_parent: 4
  death_jitter: 15
  defection_rate: 0.01
  institution_formation_rate: 0.1
  max_edges_agent: 10
  max_edges_institution: 20
